services:
  - type: web
    name: uy-ijara-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: uyijara-db
          property: connectionString
      - key: BOT_TOKEN
        value: your-telegram-bot-token